### ISSUE TITLE
Wrong wasm check results in Overview and Talk andministration pages

### ISSUE THREAD

**Issue by muchachagrande** [nextcloud/spreed#16380]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Go to Administartion -> Overview
2. The server checks are executed
3. The checks results are wrong
4. Go to Talk configuration page
5. Locate the "Web server setup checks" section
6. The check is marked in red

### Expected behaviour
There should be no configuration problems reported

### Actual behaviour
In Overview it shows a configuration problem:

Background blur
Could not check for WASM loading support. Please check manually if your web server serves `.wasm` files. To allow this check to run you have to make sure that your Web server can connect to itself. Therefore it must be able to resolve and connect to at least one of its `trusted_domains` or the `overwrite.cli.url`. This failure may be the result of a server-side DNS mismatch or outbound firewall rule.

In Talk configuration it also shows a problem:

Files required for virtual background can be loaded: NO

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)

22.0.3

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/settings/admin/talk#signaling_server`)

Using custom signaling 2.0.4

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

yes

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

yes

## Browser

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/Mac/...
Ubuntu 24.04
**Browser name:** Firefox/Chrome/Safari/...
Firefox
**Browser version:** 124/125/...
145.0.1
### Browser log

<details>
```
No errors in javascript console log
No errors in the network log
```
</details>

## Server configuration

**Operating system**: Ubuntu 22.04

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 8.3

**Nextcloud Version:** 32.0.1

**List of activated apps:**

<details>

```
Enabled:
  - activity: 5.0.0-dev.0
  - admin_audit: 1.22.0
  - app_api: 32.0.0
  - assistant: 2.9.0
  - bookmarks: 16.0.1
  - bruteforcesettings: 5.0.0-dev.0
  - calendar: 6.1.0
  - circles: 32.0.0
  - cloud_federation_api: 1.16.0
  - comments: 1.22.0
  - contacts: 8.1.0
  - contactsinteraction: 1.13.1
  - dashboard: 7.12.0
  - dav: 1.34.2
  - federatedfilesharing: 1.22.0
  - federation: 1.22.0
  - files: 2.4.0
  - files_downloadlimit: 5.0.0-dev.0
  - files_external: 1.24.0
  - files_pdfviewer: 5.0.0-dev.0
  - files_reminders: 1.5.0
  - files_sharing: 1.24.0
  - files_trashbin: 1.22.0
  - files_versions: 1.25.0
  - gpxpod: 7.1.0
  - integration_giphy: 2.2.0
  - integration_openai: 3.9.1
  - integration_openstreetmap: 3.0.0
  - integration_peertube: 2.1.0
  - integration_youtube: 0.6.1
  - keeweb: 0.6.22
  - logreader: 5.0.0-dev.0
  - lookup_server_connector: 1.20.0
  - mail: 5.6.0
  - maps: 1.6.0
  - nextcloud_announcements: 4.0.0-dev.0
  - notes: 4.12.3
  - notifications: 5.0.0-dev.0
  - notify_push: 1.2.1
  - oauth2: 1.20.0
  - password_policy: 4.0.0-dev.0
  - passwords: 2025.11.20
  - phonetrack: 0.9.1
  - photos: 5.0.0-dev.1
  - picker: 1.0.13
  - privacy: 4.0.0-dev.0
  - profile: 1.1.0
  - provisioning_api: 1.22.0
  - qownnotesapi: 25.8.0
  - recommendations: 5.0.0-dev.0
  - related_resources: 3.0.0-dev.0
  - richdocuments: 9.0.1
  - serverinfo: 4.0.0-dev.0
  - settings: 1.15.1
  - sharebymail: 1.22.0
  - sketch_picker: 2.3.0
  - socialsharing_email: 4.0.1
  - spreed: 22.0.3
  - suspicious_login: 10.0.0-dev.0
  - systemtags: 1.22.0
  - tasks: 0.17.1
  - text: 6.0.1
  - text_templates: 1.2.1
  - theming: 2.7.0
  - twofactor_backupcodes: 1.21.0
  - twofactor_email: 2.8.2
  - twofactor_nextcloud_notification: 6.0.0-dev.0
  - twofactor_totp: 14.0.0
  - updatenotification: 1.22.0
  - uppush: 2.3.1
  - user_status: 1.12.0
  - viewer: 5.0.0-dev.0
  - weather_status: 1.12.0
  - webhook_listeners: 1.3.0
  - whiteboard: 1.4.1
  - workflowengine: 2.14.0
Disabled:
  - encryption: 2.20.0
  - firstrunwizard: 5.0.0-dev.0 (installed 2.13.0)
  - support: 4.0.0-dev.0 (installed 1.7.0)
  - survey_client: 4.0.0-dev.0 (installed 1.12.0)
  - user_ldap: 1.23.0
```
</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.2.4",
            "cloud.example.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "32.0.1.2",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 60",
        "versions_retention_obligation": "auto, 180",
        "activity_expire_days": "120",
        "simpleSignUpLink.shown": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "default_phone_region": "ar",
        "logtimezone": "America\/Argentina\/Buenos_Aires",
        "default_language": "es_AR",
        "default_locale": "es_AR",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": false,
        "lost_password_link": "disabled",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Krita",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Imaginary",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Epub"
        ],
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "skeletondirectory": "",
        "theme": "",
        "filesystem_check_changes": true,
        "preview_concurrency_new": "8",
        "preview_concurrency_all": "16",
        "updater.release.channel": "stable",
        "maintenance_window_start": 1,
        "files.chunked_upload.max_size": 104857600,
        "defaultapp": "",
        "app_install_overwrite": [
            "passwords",
            "maps"
        ]
    }
}
```
</details>
Nothing on the logs
<details>

```
Nothing on the logs
```
</details>

**Comment by muchachagrande** [comment]
I checked the apache accesses while the server is performing the Overview checks and the WASM loading problem is detected because this check looks for "/spreed/js/tflite.wasm" and this file is not included in version 22.0.3. It was included in previews versions.

Then I checked apache accesses while in Talk configuration page. When I press the button to check if the virtual background files can be loaded it looks for "/apps/talk/js/vision_wasm_internal.js" and the path is wrong. I checked for "/apps/spreed/js/vision_wasm_internal.js" and the file is found, but "/apps/talk" does not exists.

EDIT:
In the Talk app the file "vision_wasm_internal.js" is loaded from the right path "/apps/spreed/js/" and it works fine.

**Comment by nickvergessen** [comment]
Fixed by https://github.com/nextcloud/spreed/pull/16389

**Comment by muchachagrande** [comment]
@nickvergessen, one of the problems described on this issue is still happening in version 22.0.4.

> Background blur
> Could not check for WASM loading support. Please check manually if your web server serves `.wasm` files. To allow this check to run you have to make sure that your Web server can connect to itself. Therefore it must be able to resolve and connect to at least one of its `trusted_domains` or the `overwrite.cli.url`. This failure may be the result of a server-side DNS mismatch or outbound firewall rule.

This is due to missing /spreed/js/tflite.wasm

EDIT:
may be this is out of Talk reach. Is on the server Overview. I've got it.

**Comment by nickvergessen** [comment]
Arg, it's too late already 🙈 

Part 2 in https://github.com/nextcloud/spreed/pull/16393

**Comment by AndyXheli** [comment]
i still see this with NC 32.0.2 running updated version talk 22.0.4 is there another version that suppose to fix this ?

<img width="1086" height="222" alt="Image" src="https://github.com/user-attachments/assets/65529f7e-c50b-444b-8c3f-f3ce95245c6e" />

**Comment by Antreesy** [comment]
> running updated version talk 22.0.4 is there another version that suppose to fix this? 

Will be shipped with the next release of 22.0.5

**Comment by Chrisi-Bavaria** [comment]
I get the same error with 23.0.3 of Talk app.

**Comment by nickvergessen** [comment]
Then you might have to do what the message says?

**Comment by blueskyfeeling** [comment]
I am getting the same error with version 24.0.5 of the Talk app. Does the problem persist?

**Comment by Antreesy** [comment]
There's no problem since 22.0.5. Please check your server configuration, as per shown on setup check

**Comment by blueskyfeeling** [comment]
@Antreesy 

Thanks for the reply. I'm not very tech-savvy. Is there a guide for this "Please check your server configuration, as per shown on setup check"? 
What exactly needs to be checked, and how should it be adjusted?

I’ve already checked a few things, such as /etc/hosts or config.php. According to the internet, everything is correct there in my case.

**Comment by Antreesy** [comment]
How this check works:
- your server makes an HTTP request to itself, using one of the domains in `trusted_domains` (config.php) or `overwrite.cli.url`.
- If that request can't complete, you get this warning; but it doesn't mean `.wasm` serving is broken
That can be additionally verified in Talk admin settings or actual Talk app by enabling virtual background

Things to be checked: on your instance, run: `curl -v https://<instance>/status.php`
Regardless if it fails or succeeds, this might give you some information to debug.  Please continue from there in internet search or on help.nextcloud.com forum

**Comment by blueskyfeeling** [comment]
Thanks a lot. Seems to be everything is correct. I will ignore this failure.
