### ISSUE TITLE
Unable to use functional TURN server

### ISSUE THREAD

**Issue by Ecphrasis** [nextcloud/spreed#197]
Hi all,

I have a fonctionnal coturn server on my dedicated server, who actually work fine with spreed.me app. I can call 3g phones, pc behind NAT, etc. nextcloud, and coturn run on the same server, without problem.
I tried the new spreed app, but I can't use my coturn server with it.
In admin additional parameters, the selection of the protocol doesn't work and create three errors : 
`Undefined index: turnServerProtocols at /var/www/nextcloud/apps/spreed/templates/settings-admin.php#35` and also 38 and 41.
In my personnal settings (what's the point to have theses settings for normal users ?), I try to fill the parameters with an user I created before on my server coturn (by the admin panel), but, same result, connection don't show in coturn admin panel...My server coturn work in the both protocols.
Have I miss something, or for the moment turn server can't be reached by the app ?

**Comment by nickvergessen** [comment]
> what's the point to have theses settings for normal users ?

https://github.com/nextcloud/spreed/issues/185

> Undefined index: turnServerProtocols at /var/www/nextcloud/apps/spreed/templates/settings-admin.php#35 and also 38 and 41.

https://github.com/nextcloud/spreed/pull/198

Regarding the "not working" cc @LukasReschke

**Comment by ernesst** [comment]
I'm able to use it with my coturn server if i set up the coturn address in the stun box setting, in admin. 
The turn box setting seems useless.
Thanks for this app simpler than spreed.me, looking for the improvement.

**Comment by tx7** [comment]
I'm having the same issue.
Any solution?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/198

**Comment by jancborchardt** [comment]
So with #198 being merged this should be fixed, closing hence. :)

**Comment by tx7** [comment]
The solution above didn't fix it.
I tried it with NC11.0.1 RC1.

**Comment by tx7** [comment]
Update: Just installed NC11.0.1 two days ago, no issue so far.

**Comment by nickvergessen** [comment]
So it works now?

**Comment by tx7** [comment]
No error so far.
