### ISSUE TITLE
[Circles] later added users not applied to Talk conversation

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#2854]
## Steps to reproduce
1. User A creates a circle "Test Circle" with User B and User C (circle type doesn't matter)
2. User A creates a conversation in Talk with "Test Circle" > A conversation "Test Circle" gets created, Users A, B and C are members of the conversation
3. User A adds User D to circle "Test Circle"

### Expected behaviour
User D gets added to the conversation "Test Circle"

### Actual behaviour
The user list remains unchanged

NC 18.0.0
Circles 0.18.0
Talk 8.0.1

**Comment by nickvergessen** [comment]
Same issue as #1329

**Comment by wiswedel** [comment]
Just for the record: Since the behavior for "share a file with a circle/group and add a member to that circle/group later" and "do the same in Talk" differs, I still see this as a UX bug, not an enhancement request.

cc @jancborchardt

**Comment by nickvergessen** [comment]
Reopening as #1329 is closed because we fixed it for groups with https://github.com/nextcloud/spreed/pull/4810
But circles is still not working

**Comment by nickvergessen** [comment]
Fixed with #5670

**Comment by shu0406** [comment]
Is https://github.com/nextcloud/spreed/pull/5670 already implemented? At our NC23.0.2 with talk13.0.3 circles are unfortunately still not updated.

**Comment by nickvergessen** [comment]
yes, there was a similar comment elsewhere recently where it worked again after retrying.
Other than that it could be a bug in the circles app.

**Comment by shu0406** [comment]
Thank, I search for that. NY retrying you mean restarting the cloud?

**Comment by g-work** [comment]
When I add a group to a circle/team, add this team to a room and then remove the group from the circle, the group members stay participants of the room. Can someone confirm this?

See https://github.com/nextcloud/spreed/issues/13569

**Comment by nickvergessen** [comment]
There is no need to bump a more than 3y old issue after raising a new one. Thanks 🙇
