### ISSUE TITLE
Path for room attachement doesn't work

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3381]
Tried with Talk 9.0.0-dev.5 on c.nc.com. I have set the path for attachments to "/Talk Attachments" but attachments are still added to my root.

**Comment by jospoortvliet** [comment]
so what happens for me and marija is that when I upload a file, it goes in the Talk folder for me but marija gets it in her root. When She uploads a file, it goes in her Talk folder but the file shows up for me in the root:
![Screenshot_20200423_142618](https://user-images.githubusercontent.com/551757/80099419-b357e480-856e-11ea-8b86-ec0b8b98d87d.png)

**Comment by nickvergessen** [comment]
Works here now with latest master of server and I expect this to be an issue that got solved in the latest beta or todays beta (due to empty owner on storage calls before).

**Comment by nickvergessen** [comment]
Also works on c.nc.c already, so closing

**Comment by schiessle** [comment]
Hm, I still have the problem on c.nc.com. Shared documents go directly to my root and not to the configured folder "/Talk Attachments"

**Comment by schiessle** [comment]
Strange thing is that I tried to reproduce it on my local dev system to collect some additional information but there it works as expected :confused:

**Comment by nickvergessen** [comment]
Yeah, I tried to debug it on our company instance already, but it seems to be caused by some random conditions. because the result is not consistent at all. it sometimes works for ABC but not DE, on the next file it works for ADE but not BC, etc.

**Comment by Dubidubiduu** [comment]
Where to set the path anyway? Haven't found an obvious setting.

And what happens when I then change from "Talk" to ".Talk"? Will that folder be moved with its content and paths will be adapted or are my users gonna get two folders, one hidden with new files, and an deprecated one with old files?

**Comment by nickvergessen** [comment]
```json
{
  "reqId": "Ix5MU8AzHd83yzoe7XX5",
  "level": 3,
  "time": "2020-09-11T09:40:59+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "files_sharing",
  "method": "",
  "url": "--",
  "message": {
    "Exception": "OCP\\Files\\NotFoundException",
    "Message": "/ not found while trying to get owner",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/apps/spreed/lib/Share/Listener.php",
        "line": 82,
        "function": "getOwner",
        "class": "OC\\Files\\View",
        "type": "->",
        "args": [
          "/"
        ]
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Share/Listener.php",
        "line": 48,
        "function": "overwriteMountPoint",
        "class": "OCA\\Talk\\Share\\Listener",
        "type": "->",
        "args": [
          {
            "__class__": "OCP\\Share\\Events\\VerifyMountPointEvent"
          }
        ]
      },
      {
        "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 251,
        "function": "listenVerifyMountPointEvent",
        "class": "OCA\\Talk\\Share\\Listener",
        "type": "::",
        "args": [
          {
            "__class__": "OCP\\Share\\Events\\VerifyMountPointEvent"
          },
          "OCP\\Share\\Events\\VerifyMountPointEvent",
          {
            "__class__": "Symfony\\Component\\EventDispatcher\\EventDispatcher"
          }
        ]
      },
      {
        "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 73,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          [
            {
              "__class__": "Closure"
            }
          ],
          "OCP\\Share\\Events\\VerifyMountPointEvent",
          {
            "__class__": "OCP\\Share\\Events\\VerifyMountPointEvent"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 86,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCP\\Share\\Events\\VerifyMountPointEvent"
          },
          "OCP\\Share\\Events\\VerifyMountPointEvent"
        ]
      },
      {
        "file": "/var/www/html/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 98,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          "OCP\\Share\\Events\\VerifyMountPointEvent",
          {
            "__class__": "OCP\\Share\\Events\\VerifyMountPointEvent"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/files_sharing/lib/SharedMount.php",
        "line": 99,
        "function": "dispatchTyped",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCP\\Share\\Events\\VerifyMountPointEvent"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/files_sharing/lib/SharedMount.php",
        "line": 80,
        "function": "verifyMountPoint",
        "class": "OCA\\Files_Sharing\\SharedMount",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Share20\\Share"
          },
          {
            "/userid/files/sparta.jpeg/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/hqdefault.jpg/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/signal-2020-03-11-133417-2.jpg/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Bildschirmfoto von 2020-03-24 21-44-52.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Screenshot_20200401_194207.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/signal-2020-03-27-123743.jpg/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Screenshot from 2020-04-08 19-27-57.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Screenshot from 2020-04-08 19-29-58.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Grid2.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            }
          },
          {
            "__class__": "OC\\Cache\\CappedMemoryCache"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/files_sharing/lib/MountProvider.php",
        "line": 124,
        "function": "__construct",
        "class": "OCA\\Files_Sharing\\SharedMount",
        "type": "->",
        "args": [
          "\\OCA\\Files_Sharing\\SharedStorage",
          {
            "/userid/files/sparta.jpeg/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/hqdefault.jpg/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/signal-2020-03-11-133417-2.jpg/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Bildschirmfoto von 2020-03-24 21-44-52.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Screenshot_20200401_194207.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/signal-2020-03-27-123743.jpg/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Screenshot from 2020-04-08 19-27-57.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Screenshot from 2020-04-08 19-29-58.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            },
            "/userid/files/Grid2.png/": {
              "__class__": "OCA\\Files_Sharing\\SharedMount"
            }
          },
          {
            "user": "userid",
            "superShare": {
              "__class__": "OC\\Share20\\Share"
            },
            "groupedShares": [
              {
                "__class__": "OC\\Share20\\Share"
              }
            ],
            "ownerView": {
              "__class__": "OC\\Files\\View"
            },
            "sharingDisabledForUser": false
          },
          {
            "__class__": "OC\\Files\\Storage\\StorageFactory"
          },
          {
            "__class__": "OC\\Files\\View"
          },
          {
            "__class__": "OC\\Cache\\CappedMemoryCache"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Config/MountProviderCollection.php",
        "line": 119,
        "function": "getMountsForUser",
        "class": "OCA\\Files_Sharing\\MountProvider",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\User\\User"
          },
          {
            "__class__": "OC\\Files\\Storage\\StorageFactory"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Filesystem.php",
        "line": 452,
        "function": "addMountForUser",
        "class": "OC\\Files\\Config\\MountProviderCollection",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\User\\User"
          },
          {
            "__class__": "OC\\Files\\Mount\\Manager"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Filesystem.php",
        "line": 377,
        "function": "initMountPoints",
        "class": "OC\\Files\\Filesystem",
        "type": "::",
        "args": [
          "userid"
        ]
      },
      {
        "file": "/var/www/html/lib/private/legacy/OC_Util.php",
        "line": 322,
        "function": "init",
        "class": "OC\\Files\\Filesystem",
        "type": "::",
        "args": [
          "userid",
          "/userid/files"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Utils/Scanner.php",
        "line": 116,
        "function": "setupFS",
        "class": "OC_Util",
        "type": "::",
        "args": [
          "userid"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Utils/Scanner.php",
        "line": 155,
        "function": "getMounts",
        "class": "OC\\Files\\Utils\\Scanner",
        "type": "->",
        "args": [
          ""
        ]
      },
      {
        "file": "/var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php",
        "line": 83,
        "function": "backgroundScan",
        "class": "OC\\Files\\Utils\\Scanner",
        "type": "->",
        "args": [
          ""
        ]
      },
      {
        "file": "/var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php",
        "line": 111,
        "function": "runScanner",
        "class": "OCA\\Files\\BackgroundJob\\ScanFiles",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\User\\User"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/BackgroundJob/Job.php",
        "line": 52,
        "function": "run",
        "class": "OCA\\Files\\BackgroundJob\\ScanFiles",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/html/lib/private/BackgroundJob/TimedJob.php",
        "line": 59,
        "function": "execute",
        "class": "OC\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 126,
        "function": "execute",
        "class": "OC\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      }
    ],
    "File": "/var/www/html/lib/private/Files/View.php",
    "Line": 1687,
    "CustomMessage": "--"
  },
  "userAgent": "--",
  "version": "20.0.0.6"
}
```
