### ISSUE TITLE
Nextcloud 18.0.4 with Talk 8.0.8: When joining a chat I get "ERROR 1052 (23000): Column 'id' in where clause is ambiguous"

### ISSUE THREAD

**Issue by apircalabu** [nextcloud/spreed#3386]
## Steps to reproduce
1. Install/upgrade to Nextcloud 18.0.4
2. Enable Talk app
3. Create a group and add several users to the group
4. Try to join a chat, or call an user. NC crashes with:

Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the
server administrator.

More details can be found in the server log.

Technical details
Remote Address: xx.xx.xx.xx
Request ID: XqJiyv8VsdSscZhz9kA@WwAAANM

### Expected behaviour
Chat / video call should work

### Actual behaviour
NC crashes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 18.0.4

**Browser name:** Firefox/Chrome/Palemoon

**Browser version:** 75.0 / 81.0.4044.113 / 28.9.1

## Talk app

**Talk app version:** 8.0.8

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: CentOS 7.7.1908

**Web server:** Apache/2.4.43

**Database:** MariaDB 10.4.12-MariaDB-log MariaDB Server

**PHP version:** PHP 7.4.5 running as php-fpm

**Nextcloud Version:** 18.0.4

**List of activated apps:**

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.9.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 0.8.2
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.5
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.3
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_external: 0.9.1
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**

`{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "next.ddns.net.au"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "https:\/\/hidden",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": "1",
        "log_type": "syslog",
        "syslog_tag": "Nextcloud",
        "logtimezone": "Australia\/Melbourne",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": false,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "hidden",
                    143,
                    "tls"
                ]
            }
        ],
        "defaultapp": "apporder",
        "maintenance": false,
        "theme": "",
        "simpleSignUpLink.shown": false
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "filesystem"
        },
        "apporder": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "1"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.0.3",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1587343821.8584",
            "lastcron": "1587700801",
            "lastupdateResult": "[]",
            "lastupdatedat": "1587697270",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "6593bb3e1b8fbe65ba88992efa03db23",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.8.2",
            "types": "dav"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "groupfolders": {
            "enabled": "yes",
            "installed_version": "6.0.5",
            "types": "filesystem,dav"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.3.3",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "3.2.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "enabled": "yes",
            "installed_version": "4.1.4",
            "types": "filesystem"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "8.0.8",
            "project_access_invalidated": "1",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.12.1",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "dav"
        },
        "theming": {
            "backgroundMime": "backgroundColor",
            "cachebuster": "18",
            "color": "#00598B",
            "enabled": "yes",
            "imprintUrl": "***REMOVED SENSITIVE VALUE***",
            "installed_version": "1.9.0",
            "logoMime": "image\/png",
            "logoheaderMime": "image\/png",
            "name": "Test NextcloudNG",
            "privacyUrl": "***REMOVED SENSITIVE VALUE***",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "updatenotification": {
            "core": "18.0.4.2",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "mail": "1.3.3",
            "types": "",
            "update_check_errors": "0"
        },
        "user_external": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "prelogin,authentication"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem"
        }
    }
}`

### Server log (data/nextcloud.log)

```
Apr 24 13:53:46 mail Nextcloud[22694]: {"reqId":"XqJiyv8VsdSscZhz9kA@WwAAANM","level":3,"time":"2020-04-24T13:53:46+10:00","remoteAddr":"xx.xx.xx.xx","user":"user@domain.tld","app":"index","method":"GET","url":"/index.php/call/h3d357zp","message":"{\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\NonUniqueFieldNameException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM `oc_talk_rooms` `r` LEFT JOIN `oc_talk_participants` `p` ON (`p`.`user_id` = ?) AND (`p`.`room_id` = `r`.`id`) WHERE (`id` = ?) AND (`p`.`user_id` IS NOT NULL)' with params [\\\"user@domain.tld\\\", 8]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous\",\"Code\":0,\"Trace\":[{\"file\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php\",\"line\":169,\"function\":\"convertException\",\"class\":\"Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php\",\"line\":145,\"function\":\"wrapException\",\"class\":\"Doctrine\\\\DBAL\\\\DBALException\",\"type\":\"::\"},{\"file\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php\",\"line\":911,\"function\":\"driverExceptionDuringQuery\",\"class\":\"Doctrine\\\\DBAL\\\\DBALException\",\"type\":\"::\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/DB/Connection.php\",\"line\":199,\"function\":\"executeQuery\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php\",\"line\":200,\"function\":\"executeQuery\",\"class\":\"OC\\\\DB\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php\",\"line\":215,\"function\":\"execute\",\"class\":\"Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/apps/spreed/lib/Manager.php\",\"line\":265,\"function\":\"execute\",\"class\":\"OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/apps/spreed/lib/Controller/PageController.php\",\"line\":182,\"function\":\"getRoomForParticipant\",\"class\":\"OCA\\\\Talk\\\\Manager\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/apps/spreed/lib/Controller/PageController.php\",\"line\":119,\"function\":\"index\",\"class\":\"OCA\\\\Talk\\\\Controller\\\\PageController\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":170,\"function\":\"showCall\",\"class\":\"OCA\\\\Talk\\\\Controller\\\\PageController\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":99,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/App.php\",\"line\":125,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php\",\"line\":47,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\"},{\"function\":\"__invoke\",\"class\":\"OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/Route/Router.php\",\"line\":299,\"function\":\"call_user_func\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/base.php\",\"line\":1008,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/index.php\",\"line\":38,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\"}],\"File\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php\",\"Line\":65,\"Previous\":{\"Exception\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDOException\",\"Message\":\"SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous\",\"Code\":\"23000\",\"Trace\":[{\"file\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php\",\"line\":903,\"function\":\"execute\",\"class\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDOStatement\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/DB/Connection.php\",\"line\":199,\"function\":\"executeQuery\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php\",\"line\":200,\"function\":\"executeQuery\",\"class\":\"OC\\\\DB\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php\",\"line\":215,\"function\":\"execute\",\"class\":\"Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/apps/spreed/lib/Manager.php\",\"line\":265,\"function\":\"execute\",\"class\":\"OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/apps/spreed/lib/Controller/PageController.php\",\"line\":182,\"function\":\"getRoomForParticipant\",\"class\":\"OCA\\\\Talk\\\\Manager\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/apps/spreed/lib/Controller/PageController.php\",\"line\":119,\"function\":\"index\",\"class\":\"OCA\\\\Talk\\\\Controller\\\\PageController\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":170,\"function\":\"showCall\",\"class\":\"OCA\\\\Talk\\\\Controller\\\\PageController\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":99,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/App.php\",\"line\":125,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php\",\"line\":47,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\"},{\"function\":\"__invoke\",\"class\":\"OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/Route/Router.php\",\"line\":299,\"function\":\"call_user_func\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/base.php\",\"line\":1008,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/index.php\",\"line\":38,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\"}],\"File\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php\",\"Line\":119,\"Previous\":{\"Exception\":\"PDOException\",\"Message\":\"SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous\",\"Code\":\"23000\",\"Trace\":[{\"file\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php\",\"line\":117,\"function\":\"execute\",\"class\":\"PDOStatement\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php\",\"line\":903,\"function\":\"execute\",\"class\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDOStatement\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/DB/Connection.php\",\"line\":199,\"function\":\"executeQuery\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php\",\"line\":200,\"function\":\"executeQuery\",\"class\":\"OC\\\\DB\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php\",\"line\":215,\"function\":\"execute\",\"class\":\"Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/apps/spreed/lib/Manager.php\",\"line\":265,\"function\":\"execute\",\"class\":\"OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/apps/spreed/lib/Controller/PageController.php\",\"line\":182,\"function\":\"getRoomForParticipant\",\"class\":\"OCA\\\\Talk\\\\Manager\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/apps/spreed/lib/Controller/PageController.php\",\"line\":119,\"function\":\"index\",\"class\":\"OCA\\\\Talk\\\\Controller\\\\PageController\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":170,\"function\":\"showCall\",\"class\":\"OCA\\\\Talk\\\\Controller\\\\PageController\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":99,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/App.php\",\"line\":125,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php\",\"line\":47,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\"},{\"function\":\"__invoke\",\"class\":\"OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/private/Route/Router.php\",\"line\":299,\"function\":\"call_user_func\"},{\"file\":\"/var/www/html/hidden/nextcloud/lib/base.php\",\"line\":1008,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\"},{\"file\":\"/var/www/html/hidden/nextcloud/index.php\",\"line\":38,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\"}],\"File\":\"/var/www/html/hidden/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php\",\"Line\":117}},\"CustomMessage\":\"--\"}","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36","version":"18.0.4.2"}
```

### Additional information
I get error 1052 in mysql when I run this query:
```
MariaDB [nextcloud]> SELECT * FROM `oc_talk_rooms` `r` LEFT JOIN `oc_talk_participants` `p` ON (`p`.`user_id` = 'user@domain.tld') AND (`p`.`room_id` = `r`.`id`) WHERE (`id` = 3) AND (`p`.`user_id` IS NOT NULL);
```
```
ERROR 1052 (23000): Column 'id' in where clause is ambiguous
```

**Comment by apircalabu** [comment]
Imported the db schema on an ubuntu 18.0.4 machine running MySQL Server version: 5.7.29-0ubuntu0.18.04.1 (Ubuntu) and ran the same query with the same `ERROR 1052 (23000): Column 'id' in where clause is ambiguous` result.

**Comment by nickvergessen** [comment]
Fixed in #3447

**Comment by apircalabu** [comment]
The error's gone after applying the patch, thanks. However, I'm still having issues with getting 2 users in the same group to send messages to each other in a group conversation, will keep digging into it. Cheers.
