### ISSUE TITLE
Guest chat removable by other logged in user

### ISSUE THREAD

**Issue by Millesimus** [nextcloud/spreed#4707]
## Steps to reproduce
1. Create group chat with guest link using account A
2. Open guest link with account B logged in
3. Click "leave chat" with account B

### Expected behaviour
The respective group chat should be simply removed from the Talk overview page of account B, but still present for account A and accessible via the share link.

### Actual behaviour
The respective group chat is deleted completely, i.e. also for the original creator (account A).

## Talk app

**Talk app version:** 9.0.6

## Server configuration

**Nextcloud Version:** 19.0.5

**Comment by PVince81** [comment]
I couldn't reproduce this with NC 20.0.0 and Talk 10.0.1.

maybe this got fixed in a more recent version ?

**Comment by Millesimus** [comment]
Thanks for your input. I have just reproduced the error with NC 20.0.4 and Talk 10.0.4, so it is still present.

**Comment by Millesimus** [comment]
Can confirm issue is gone in Talk 10.0.5 on NC 20.0.4.

**Comment by nickvergessen** [comment]
Thanks!
