### ISSUE TITLE
linked files and folders missing in conversations

### ISSUE THREAD

**Issue by MiMoV119** [nextcloud/spreed#5451]
## Steps to reproduce
1. open nextcloud website in browser
2. go to "Talk"
3. open a conversation
4. open sidebar with members and setings
5. view settings
6. open another conversation
7. look in settings

### Expected behaviour
- for both conversations files and/or folders are linked

### Actual behaviour
- only the first conversation opened after reloading talk app shows the linked files/folders
- every conversation after opening a conversation the first time after reloading talk app does not show the linked files/folders

## Talk app

**Talk app version: 10.0.6**

**Custom Signaling server configured: no**

**Custom TURN server configured: yes**

**Custom STUN server configured: no**

## Browser

**Operating system: Windows**

**Browser name: Firefox & Chrome**

**Browser version: Firefox 87.0 & Chrome 89.0.4389.114**

**Operating system**: Ubuntu
**Web server:** Apache
**Database:** PostgreSQL
**PHP version:** 7.4
**Nextcloud Version:** 20.0.8

**List of activated apps:**

<details>
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - announcementcenter: 4.0.1
  - calendar: 2.2.0
  - circles: 0.20.7
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.5
  - extract: 1.3.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_fulltextsearch: 20.0.1
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.2.4
  - fulltextsearch: 20.0.0
  - fulltextsearch_elasticsearch: 20.0.0
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - nextnote: 1.2.5
  - notes: 4.0.4
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - pdfdraw: 0.1.2
  - photos: 1.2.3
  - polls: 1.8.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - qownnotesapi: 20.9.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.17
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.6
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - issuetemplate
  - ocr
</details>

**Comment by nickvergessen** [comment]
We fixed this with 10.0.6
https://github.com/nextcloud/spreed/pull/5142

**Comment by MiMoV119** [comment]
We are using 10.0.6 and still have this issue.
The linked resources are shown only for the first conversation opened after opening talk or doing a full reload of the talk page (click talk icon in top menu of nextcloud webinterface).
If I open other conversations the list of linked resources is empty. If I open the conversation first opened after a reload the resources for this conversation are shown.

**Comment by MiMoV119** [comment]
We are now at version 12.2.2 and still facing the described problem.
Any idea how to fix that?
